### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Pietsupply** [Cellebyte/wichtelit#31]
- [ ] Adding Wishlists to every member, so the others can have some inspiration on what to gift.
- [ ] Cleaning up the File and Variable names and adding comments for better understanding.
- [ ] Adding an Email for successful registration
- [ ] Better representation of the Mail for mobile devices 
- [ ] Make the Email design better
